apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sopes2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: pablopachecof/so2backend
        name: so2backend
        command: [ "npm", "run", "dev" ]
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sopes2
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: backend
  type: LoadBalancer
